# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(rhino)
# remotes::install_github("Appsilon/shiny.react")
# remotes::install_github("Appsilon/shiny.fluent")
library(shiny.fluent)
# remotes::install_github("Appsilon/shiny.router")
library(shiny.router)
library(purrr)
library(shiny)
# install.packages("shiny.semantic")
library(shiny.semantic)
# install.packages("shinyjs")
library(shinyjs)
# install.packages("dplyr")
library(data.table)
library(leaflet)
library(DT)
library(mongolite)
library(dplyr)
